### ISSUE TITLE
ValueError: squeeze_dims[0] not in [-1,1). for 'Squeeze' (op: 'Squeeze') with input shapes: [100].

### ISSUE THREAD

**Issue by khurram18** [dddoss/tensorflow-socher-ntn#7]
```
Tensor("split:0", shape=(), dtype=int32) Tensor("split:1", shape=(), dtype=int32) Tensor("split:2", shape=(), dtype=int32)
Traceback (most recent call last):
  File "ntn_train.py", line 110, in <module>
    tf.app.run()
  File "/Users/khurram/anaconda3/envs/tf2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "ntn_train.py", line 107, in main
    run_training()
  File "ntn_train.py", line 79, in run_training
    num_entities, num_relations, slice_size, batch_size, False, label_placeholders, start_time)
  File "/Users/khurram/Development/tensorflow-socher-ntn/code/ntn.py", line 50, in inference
    e1v = tf.transpose(tf.squeeze(tf.gather(entEmbed, e1, name='e1v'+str(r)), [1]))
  File "/Users/khurram/anaconda3/envs/tf2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2490, in squeeze
    return gen_array_ops._squeeze(input, axis, name)
  File "/Users/khurram/anaconda3/envs/tf2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5273, in _squeeze
    "Squeeze", input=input, squeeze_dims=axis, name=name)
  File "/Users/khurram/anaconda3/envs/tf2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/khurram/anaconda3/envs/tf2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3162, in create_op
    compute_device=compute_device)
  File "/Users/khurram/anaconda3/envs/tf2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3208, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/Users/khurram/anaconda3/envs/tf2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2427, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/Users/khurram/anaconda3/envs/tf2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2400, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/khurram/anaconda3/envs/tf2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2330, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/Users/khurram/anaconda3/envs/tf2/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/Users/khurram/anaconda3/envs/tf2/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: squeeze_dims[0] not in [-1,1). for 'Squeeze' (op: 'Squeeze') with input shapes: [100].
```

**Comment by Yshihui** [comment]
I meet the same mistake.Have you corrected this mistake? how? thank you
